services:
  - type: web
    name: name: production-player-cloud-premium
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DESKTOP_SECRET
        value: 3-9JyxVj5b0ji0os_e7HFEuqEsAmQj6L4ZsFbuiZgvE
